db: "mysql://root:root@localhost:3376/lnvps"
lightning:
  lnd:
    url: "https://127.0.0.1:10003"
    cert: "/home/kieran/.polar/networks/2/volumes/lnd/alice/tls.cert"
    macaroon: "/home/kieran/.polar/networks/2/volumes/lnd/alice/data/chain/bitcoin/regtest/admin.macaroon"
delete-after: 3
public-url: "https://api.lnvps.net"
redis:
  url: "redis://localhost:6398"
  ttl: 30
encryption:
  key-file: "encryption.key"
  auto-generate: true
provisioner:
  proxmox:
    read-only: false
    qemu:
      bios: "ovmf"
      machine: "q35"
      os-type: "l26"
      bridge: "vmbr0"
      cpu: "host"
      vlan: 100
      kvm: false
# Captcha is used in various places to prevent spam
captcha:
  # Turnstile is a Cloudflare captcha product
  turnstile:
    secret-key: "1x0000000000000000000000000000000AA"