name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.v0l.io
          username: registry
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push lnvps-api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: lnvps_api/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          tags: registry.v0l.io/lnvps-api:latest

      - name: Build and push lnvps-api-admin
        uses: docker/build-push-action@v5
        with:
          context: .
          file: lnvps_api_admin/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          tags: registry.v0l.io/lnvps-api-admin:latest

      - name: Build and push lnvps-operator
        uses: docker/build-push-action@v5
        with:
          context: .
          file: lnvps_operator/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          tags: registry.v0l.io/lnvps-operator:latest
