name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: lnvps-api
            file: lnvps_api/Dockerfile
            image: registry.v0l.io/lnvps-api:latest
          - name: lnvps-api-admin
            file: lnvps_api_admin/Dockerfile
            image: registry.v0l.io/lnvps-api-admin:latest
          - name: lnvps-operator
            file: lnvps_operator/Dockerfile
            image: registry.v0l.io/lnvps-operator:latest
          - name: lnvps-nostr
            file: lnvps_nostr/Dockerfile
            image: registry.v0l.io/lnvps-nostr:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.v0l.io
          username: registry
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          tags: ${{ matrix.image }}
